# Builds all the projects in the solution...
.PHONY: all_projects
all_projects: np_node 

# Builds project 'np_node'...
.PHONY: np_node
np_node: 
	make --directory="np_node/" --file=np_node.makefile

# Cleans all projects...
.PHONY: clean
clean:
	make --directory="np_node/" --file=np_node.makefile clean

